name: dev-gateway

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "빌드할 git ref (브랜치명)"
        required: true

jobs:
  call:
    uses: ./.github/workflows/_dev-build.yml
    with:
      service: gateway
      ecr_repo: eks-practice-api-gateway-dev
      ref: ${{ github.event.inputs.ref }}
      role_arn: arn:aws:iam::657231015203:role/eks-practice-gateway-github
