name: dev-gateway

on:
  push:
    branches-ignore: [main]
    paths:
      - "services/gateway/**"

jobs:
  call:
    uses: ./.github/workflows/_dev-build.yml
    with:
      service: gateway
      ecr_repo: eks-practice-api-gateway-dev
      role_arn: arn:aws:iam::657231015203:role/eks-practice-gateway-github
